version: "3.8"

services:
  # this server is the entrypoint of http request
  server:
    # image: 'nginx:stable-alpine'
    # for production, copy src to /var/www/html
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    # bind mount is useful for development, not for production
    # volumes: 
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mysql
    container_name: nginx-server
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    # volumes:
    #   - ./src:/var/www/html:delegated
    container_name: php-container
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    container_name: mysql-db
  # util container
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:16-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html