version: "3.8"

services:
  # this server is the entrypoint of http request
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mysql
    container_name: nginx-server
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php-container
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    container_name: mysql-db
  # util container
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm: